disabled = false
locale = "zh-cn"
label = "中文"
weight = 1
title = "Blogus Chii"

[params]
  displayName = "中文"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2006年1月2日"
  description = "Chius 的博客"

[params.author]
  name = "Chius"
  image = "img/chius-pixel.compression.png"
  headline = "我们所度过的每个平凡的日常 也许就是连续发生的奇迹"

  [[params.author.links]]
    envelope = "mailto:contact@chius.cc"
  [[params.author.links]]
    github = "https://github.com/chius-me"
  [[params.author.links]]
    rss = "https://chius.cc/index.xml"
