[[main]]
  name = "文章"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "嘟嘟"
  pageRef = "fediverse"
  weight = 17

[[main]]
  name = "归档"
  pageRef = "archives"
  weight = 20

[[main]]
  name = "标签"
  pageRef = "tags"
  weight = 30

[[main]]
  name = "友链"
  pageRef = "friends"
  weight = 35

[[main]]
  name = "关于"
  pageRef = "about"
  weight = 40

[[main]]
  name = "文件分享"
  url = "https://ilist.chius.cc"
  weight = 42
  [main.params]
    target = "_blank"

[[main]]
  name = "社交链接"
  url = "/links/"
  weight = 45
  [main.params]
    target = "_blank"

[[main]]
  name = "简历"
  url = "/cv.pdf"
  weight = 50
  [main.params]
    target = "_blank"
